### ISSUE TITLE
Login-Tracking

### ISSUE THREAD

**Issue by meisl** [meisl/hafis#11]
- [x] 24.09.2018, 23:15                                      Uhr | Windows XP | Firefox 52.0 | München
- [x] 24.09.2018, 17:39                                      Uhr | Windows XP | Firefox 52.0 | München
- [x] 24.09.2018, 08:21                                      Uhr | Windows | Chrome 69.0 | München
- [x] 23.09.2018, 18:40                                      Uhr | Windows XP | Firefox 52.0 | München
- [x] 22.09.2018, 21:11                                      Uhr | Windows XP | Firefox 52.0 | München
- [x] 22.09.2018, 16:39                                      Uhr | Windows XP | Firefox 52.0 | München
- [x] 22.09.2018, 16:34                                      Uhr | Windows XP | Firefox 52.0 | München
- [x] 22.09.2018, 13:21                                      Uhr | Windows 7 | Chrome 69.0 | München
- [x] 22.09.2018, 11:47                                      Uhr | Windows 7 | Chrome 69.0 | München
- [x] 22.09.2018, 10:44                                      Uhr | Windows XP | Chrome 49.0 | München
- [x] 22.09.2018, 10:43                                      Uhr | Windows XP | Chrome 49.0 | München
- **??? 21.09.2018, 18:58                                      Uhr | Windows | Chrome 69.0 | Cleebronn**
- [x] 21.09.2018, 16:52                                      Uhr | Linux (Ubuntu) | Chromium 66.0 | München
- [x] 20.09.2018, 21:36                                      Uhr | Windows | Chrome 69.0 | Regensburg
- [x] 20.09.2018, 11:38                                      Uhr | Windows | Chrome 69.0 | Regensburg
- [x] 19.09.2018, 22:59                                      Uhr | Windows | Chrome 69.0 | Regensburg

**Comment by chdoerr** [comment]
Genau, gestern morgen war`s ich -abgehakt!
Regensburg weiß ich nicht, muss mal im Browserverlauf schaun- Moment- okay: alles ich!
Bleibt noch Cleebronn: War auch ich...komisch

**Comment by chdoerr** [comment]
#11 Höchstwahrscheinlich also falscher Alarm - vermutlich können wir #11 schließen- was meinst Du?

**Comment by meisl** [comment]
Ok
