### ISSUE TITLE
Hafis-Logo

### ISSUE THREAD

**Issue by meisl** [meisl/hafis#33]
Dass wir was am Logo machen müssen ist schon länger klar. Aktueller Anlass ist das fürchterlich schlechte Logo von Hafis, das aktuell auf der [Weissensee-HP](https://gsweiss.musin.de/zusatzangebote/) zu sehen ist (sh. #31):
![hafis-e v -logo-2016-j-e1544036687234](https://user-images.githubusercontent.com/1493886/49678577-8bed9e00-fa85-11e8-8e89-b28473794dce.jpeg)

### Probleme ###
Das Thema "Logo" hat mehrere Aspekte, die man am Ende auch nicht unabhängig betrachten kann. Ich versuche es mal so ordnen:
1. Reine Bildqualität: je nach Verwendungszweck brauchen wir das Logo in verschiedenen Größen. Aktuell haben wir i.W. nur ein jpg in 880x129 nominell, 878x89 effektiv. Mit Artefakten:
![logo-2016-j](https://user-images.githubusercontent.com/1493886/49677936-b0e01200-fa81-11e8-8321-187e965eb7b7.jpg)
2. Gestaltung: naja, ich sag mal so: nicht alles ist reine Geschmackssache... Außerdem kann man ein Logo durchaus je nach Verwendungszweck ein wenig variieren. Einfach damit es im jeweiligen Kontext bestmöglich wirkt - und trotzdem natürlich eindeutig wiedererkannt wird.
3. Arbeitsgrundlagen: für jegliche Verbesserung von sowohl 1. als auch 2. braucht es vernünftige Arbeitsdateien. Diese sollten in sehr guter Qualität bzw. beliebig skalierbar (Vektorgrafik) vorliegen. Außerdem bräuchte es ein dokumentiertes Konzept. Was wir haben ist nur das obige jpg...
4. Das Logo tatsächlich online zu stellen ist nicht so einfach wie man denken könnte: #35 

### Aufgaben ###
Dokumentation der erledigten Aufgaben nicht nur in div. Bilddateien sondern auch in `.md`s unter [`/Logo/`](https://github.com/meisl/hafis/blob/master/Logo/) im repo.
* Ziele definieren: [`/Logo/README.md`](https://github.com/meisl/hafis/blob/master/Logo/README.md)
  - [ ] Qualitätskriterien bzgl. 1., 2. und 3. von oben
  - [x] Zielformate bzw. gewünschte Verwendungszwecke
* Konsolidierung:
  - [x] Bestandsaufnahme und aufräumen:  [`/Logo/status-quo-2018-12/README.md`](https://github.com/meisl/hafis/blob/master/Logo/status-quo-2018-12/README.md)
  - [ ] Nachbauen des derzeitigen Designs (es gibt nur eins) in guter Qualität, soviel Vektor wie möglich: 06af1787f7f5ba405efac54fba3085a84e59e4d3 bzw. [das daraus erzeugte .png](https://github.com/meisl/hafis/blob/a84009f4043ca5189379febd33e04634cc421cd9/MyWebsite/Bilder/Logo/Logo_Hafis-2016_HP-Titel.png). Was noch fehlt ist die Schrift als Vektoren.
  - [x] Stelle das bessere Logo online (-> #35 !)
  - [ ] entspr. #35: räume `/MyWebsite/Bilder/Logo` auf
  - [x] entspr. #35: erstelle `/MyWebsite/Design/Dateien`
  - [ ] Analyse des derzeitigen Designs: was sind die einzelnen Elemente und ihre Bedeutung? Warum ist was wie und wie groß wo angeordnet?
  - [x] Erstellen einer qualitativ hochwertigen Version des derzeitigen Designs in der Breite 220px und etwa 30-40px hoch:
    * ![](https://github.com/meisl/hafis/raw/2fa94d35c9c0a06a1084423f4a983a46cf65bb28/Logo/Logo_Hafis-2016_221x32.png)
    * Arbeitsdatei: [`/Logo/Logo_Hafis-2016_221x32.xcf`](https://github.com/meisl/hafis/raw/2fa94d35c9c0a06a1084423f4a983a46cf65bb28/Logo/Logo_Hafis-2016_221x32.xcf)
* Neugestaltung:
  - [ ]  Schriftzug "Hafis e.V."
  - [ ] die Eule
  - [ ] der "Regenbogen"
  - [ ] evtl. andere Elemente
  - [ ] für jeden gewünschten Zweck/jedes Format möglichst mehrere Variationen
    * erste Ergebnisse für "klein" (ca 220 px breit): [/Logo/Logo-klein.md](https://github.com/meisl/hafis/blob/master/Logo/Logo-klein.md). Das momentan beste ist
    ![logo_hafis-2018_02c-klein](https://user-images.githubusercontent.com/1493886/49763499-1c69ef80-fccd-11e8-8b67-70eea59fab8b.png)

**Comment by meisl** [comment]
Update nach gestrigem Gespräch mit Kruno:
die Eule hat er gar nicht selber gemalt, sondern aus dem animierten gif extrahiert, welches er von irgendwo her hatte. Leider wirklich nur in dieser Größe.

-> Eule neu malen, in Inkscape (!)

**Comment by chdoerr** [comment]
Petras Aufgabe
